<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/22
 * Time: 23:05
 */

namespace Common\Model;


use Think\Model;

class CommonModel extends Model
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}