<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/22
 * Time: 23:05
 */

namespace Common\Model;


use Think\Model;

class CommonModel extends Model
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 根据id获取记灵
     *
     * @param integer $id
     * @param string $fields
     * @return array
    */
    public function info($id, $fields = '*')
    {
        $arr_map =[];
        $str_pkId = $this->getPk();
        $arr_map[$str_pkId] = $id;
        return $this->field($fields)->where($arr_map)->find();
    }

    /**
     * 更新数据库
     *
     * @param array $data
     * @param integer $id
     * @return void
    */
    public function update($data, $id)
    {
        return $this->where([$this->getPk() => $id])->save($data);
    }

}