<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/23
 * Time: 22:58
 */

namespace Admin\Controller;


class PublicController extends CommonController
{

    /**
     * 初始化函数
     *
     * @reture void;
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 管理员登录
     *
     * @return void
    */
    public function login()
    {
        $this->display();
    }
}