<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/7
 * Time: 21:54
 */

namespace Admin\Controller;


class QuestionController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 问题列表
     *
     * @return void
    */
    public function index()
    {
        $int_page = I('get.p');
        $int_page = max($int_page, 1);
        $int_pagesize = 10;

        $arr_map = $arr_question = [];

        $int_total = D('Common/Question')->where($arr_map)->count();
        if ($int_total) {
            $arr_question = D('Common/Question')->where($arr_map)->page($int_page, $int_pagesize)->order('id DESC')->select();
        }

        //$str_pagebar = showAdmin($int_total, $int_pagesize);

        $this->assign('pages', $str_pagebar);
        $this->assign('data', $arr_question);
        $this->display();
    }

    /**
     * 添加问题
     *
     * @return void
    */
    public function add()
    {
        if (IS_POST) {

        } else {

        }
    }

    /**
     * 获取请求数据
     *
     * @param bool $bool_IsEdit
     * @return array
     */
    private function getPostData($bool_IsEdit = false)
    {
        $arr_Post = $this->getData();

        $arr_Data = [];
        $arr_Data['category1'] = (int)$arr_Post['category1'];
        $arr_Data['category2'] = (int)$arr_Post['category2'];
        $arr_Data['category3'] = (int)$arr_Post['category3'];
        if (!$arr_Post['question']) {
            message('必须问题内容', 3);
        }
        $arr_Data['question'] = $arr_Post['question'];
        $arr_Data['describe'] = (string)$arr_Post['describe'];

        $arr_map = [];
        $arr_map['question'] = $arr_Data['question'];
        if ($bool_IsEdit) {
            $id = $this->getData('id');
            $arr_map['id'] = ['neq', $id];
        }
        if (D('Common/Question')->where($arr_map)->count() > 0) {
            message('当前问题已存在', 3);
        }
        $arr_Data['status'] = (int)$arr_Post['status'];

        return $arr_Data;
    }
}